### ISSUE TITLE
Does not write the data to graphite

### ISSUE THREAD

**Issue by saxena-gaurav** [fatelei/nodegraphite#1]
Hi,

I was not able to write the metrics data to graphite. below is the sample application i wrote:

var GraphiteClient = require("./lib/graphite").GraphiteClient;
var gc = new GraphiteClient(2003, 'graphite.example.com');

var metrics = {foo2_bar: 30};
gc.write(metrics, function(err) {
  console.log(err);
  console.log(metrics);
});

The err printed from above console log is 'undefined'. In your javascript file graphite.js neither error listener got called nor the data listener. Can you check what's wrong ?

**Comment by fatelei** [comment]
I'm so sorry, I find issue until now. I will figure out what's wrong as soon as possible.

**Comment by fatelei** [comment]
@saxena-gaurav , I add a error event to `nodegraphite`, you can add an event listener to it, to see whether there is an error occurs.

**Comment by fatelei** [comment]
@saxena-gaurav , you should use `nodegraphite == 2.0.1`.
